apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aks-proget-poc-msi
  namespace: proget
spec:
  provider: azure
  parameters:
    cloudName: ""
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    tenantId: 8ac76c91-e7f1-41ff-a89c-3553b2da2c17 # replace with Terraform ouput aks_identity_tenant_id>
    keyvaultName: a88abe4f-9fca-4cd4-8eae-821030b87d1f # replace with Terraform ouput key_vault_name
    userAssignedIdentityID: akssecretsstoretutorial1 # replace with Terraform ouput aks_key_vault_identity_client_id
    objects: |
      array:
        - |
          objectName: sql-connection-string
          objectType: secret
          objectVersion: ""
  secretObjects:
  - data:
    - key: PROGET_SQL_CONNECTION_STRING
      objectName: sql-connection-string
    secretName: sql-connection-string
    type: Opaque
