apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aks-proget-poc-msi
  namespace: proget
spec:
  provider: azure
  parameters:
    cloudName: ""
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    tenantId: <output-aks_identity_tenant_id>
    keyvaultName: <output-key_vault_name>
    userAssignedIdentityID: <aks_key_vault_identity_client_id>
    objects: |
      array:
        - |
          objectName: sql-connection-string
          objectType: secret
          objectVersion: ""
  secretObjects:
  - data:
    - key: PROGET_SQL_CONNECTION_STRING
      objectName: sql-connection-string
    secretName: sql-connection-string
    type: Opaque
